export interface AuditEvent {
  id?: string;                     // UUID v4 generated by the application
  type: string;                    // Event type, e.g. "login", "update", "delete"
  category?: string;               // Logical grouping, e.g. "auth", "db-change", "access"
  userId?: string;                 // ID of the user who triggered the event
  ip?: string;                     // Originating IP address
  endpoint?: string;               // URL/route that was accessed
  method?: string;                 // HTTP method: GET, POST, PUT, DELETE
  statusCode?: number;             // HTTP response status code
  action: string;                  // Short description of the action performed
  description?: string;            // Detailed description of the event
  payload?: any;                   // Additional event data (structured as JSON)
  createdAt: Date;                 // Timestamp when the event occurred
  responseTime?: number;           // Response time in milliseconds
  userAgent?: string;              // Request User-Agent header
  metadata?: Record<string, any>;  // Custom extra information (key-value pairs)
}
